import Head from "next/head";
import Card from "../components/atoms/Card";
import styled from "styled-components";
import { BsGithub } from "react-icons/bs";
import { BsInstagram } from "react-icons/bs";
import { SiGmail } from "react-icons/si";
import Sns from "../components/atoms/Sns";
import Footer from "../components/molecules/Footer";
export default function Home() {
  function handleClick() {
    console.log("increment like count");
  }
  return (
    <>
      <Head>
        <title> LUCY&apos;S LOG </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "0 2rem" }}>
        <section
          style={{
            minHeight: "100vh",
            padding: "4rem 0",
            flex: 1,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <HeaderWrap>
            <h1 className="title">
              Welcome to <a href="">Lucy&apos;s Log</a>
            </h1>
            <p className="description">
              Get started by editing
              <code className="code">pages/index.js</code>
            </p>
          </HeaderWrap>

          <Container>
            <Card cardtitle="GitHub" link="https://github.com/Garam-Leee" />
            <Card cardtitle="Blog" link="/Blog" />
            <Card cardtitle="Read ME" link="/ReadMe" />
            <Card cardtitle="Diary" link="/Diary" />
          </Container>
        </section>
      </div>
    </>
  );
}

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 900px;
  @media (max-width: 600px) {
    .grid {
      width: 100%;
      flex-direction: column;
    }
  }
`;

const HeaderWrap = styled.div`
  .title {
    margin: 0;
    line-height: 1.15;
    font-size: 4rem;
  }
  .title a {
    color: #0070f3;
    text-decoration: none;
  }

  .title a:hover,
  .title a:focus,
  .title a:active {
    text-decoration: underline;
  }

  .description {
    margin: 4rem 0;
    text-align: center;
    line-height: 1.5;
    font-size: 1.5rem;
  }
`;
